-- MASTER SCRIPT TO ALIGN SUPABASE SCHEMA WITH LOCAL KONTIGO DATA
-- Run this in the Supabase SQL Editor to parse all local fields and stop errors.

-- 1. RESTAURANT STAFF (Chilean Payroll Fields & Personal Info)
ALTER TABLE restaurant_staff ADD COLUMN IF NOT EXISTS role_name TEXT; -- Mapping target for 'role'
ALTER TABLE restaurant_staff ADD COLUMN IF NOT EXISTS status TEXT DEFAULT 'active'; -- Target for 'active' boolean
ALTER TABLE restaurant_staff ADD COLUMN IF NOT EXISTS address TEXT;
ALTER TABLE restaurant_staff ADD COLUMN IF NOT EXISTS phone TEXT;
ALTER TABLE restaurant_staff ADD COLUMN IF NOT EXISTS email TEXT;
ALTER TABLE restaurant_staff ADD COLUMN IF NOT EXISTS avatar_color TEXT;

-- Payroll / HR Fields
ALTER TABLE restaurant_staff ADD COLUMN IF NOT EXISTS rut TEXT;
ALTER TABLE restaurant_staff ADD COLUMN IF NOT EXISTS nationality TEXT;
ALTER TABLE restaurant_staff ADD COLUMN IF NOT EXISTS birth_date TIMESTAMP WITH TIME ZONE;
ALTER TABLE restaurant_staff ADD COLUMN IF NOT EXISTS working_hours_limit INTEGER; -- 'weeklyHoursLimit' mapping

-- Contract Info
ALTER TABLE restaurant_staff ADD COLUMN IF NOT EXISTS contract_type TEXT;
ALTER TABLE restaurant_staff ADD COLUMN IF NOT EXISTS contract_duration TEXT;
ALTER TABLE restaurant_staff ADD COLUMN IF NOT EXISTS start_date TIMESTAMP WITH TIME ZONE;

-- Salary & Benefits
ALTER TABLE restaurant_staff ADD COLUMN IF NOT EXISTS salary_type TEXT;
ALTER TABLE restaurant_staff ADD COLUMN IF NOT EXISTS base_salary NUMERIC;
ALTER TABLE restaurant_staff ADD COLUMN IF NOT EXISTS gratification BOOLEAN;
ALTER TABLE restaurant_staff ADD COLUMN IF NOT EXISTS colacion NUMERIC;
ALTER TABLE restaurant_staff ADD COLUMN IF NOT EXISTS movilizacion NUMERIC;
ALTER TABLE restaurant_staff ADD COLUMN IF NOT EXISTS estimated_tips NUMERIC;

-- Health & Pension (Chile Specific)
ALTER TABLE restaurant_staff ADD COLUMN IF NOT EXISTS afp TEXT;
ALTER TABLE restaurant_staff ADD COLUMN IF NOT EXISTS health_system TEXT;
ALTER TABLE restaurant_staff ADD COLUMN IF NOT EXISTS health_fee NUMERIC;
ALTER TABLE restaurant_staff ADD COLUMN IF NOT EXISTS seguro_cesantia BOOLEAN;

-- Banking
ALTER TABLE restaurant_staff ADD COLUMN IF NOT EXISTS bank_details JSONB; -- Store complex 'bankDetails' object as JSON

-- 2. INGREDIENTS (New Inventory Categorization)
ALTER TABLE ingredients ADD COLUMN IF NOT EXISTS family TEXT;
ALTER TABLE ingredients ADD COLUMN IF NOT EXISTS sub_family TEXT;
ALTER TABLE ingredients ADD COLUMN IF NOT EXISTS storage TEXT;
ALTER TABLE ingredients ADD COLUMN IF NOT EXISTS is_infinite BOOLEAN DEFAULT FALSE;
ALTER TABLE ingredients ADD COLUMN IF NOT EXISTS purchase_unit TEXT;
ALTER TABLE ingredients ADD COLUMN IF NOT EXISTS conversion_factor NUMERIC DEFAULT 1;
ALTER TABLE ingredients ADD COLUMN IF NOT EXISTS code TEXT;
ALTER TABLE ingredients ADD COLUMN IF NOT EXISTS yield_percent NUMERIC DEFAULT 100;

-- Preparation / Sub-recipe fields
ALTER TABLE ingredients ADD COLUMN IF NOT EXISTS is_preparation BOOLEAN DEFAULT FALSE;
ALTER TABLE ingredients ADD COLUMN IF NOT EXISTS recipe JSONB;
ALTER TABLE ingredients ADD COLUMN IF NOT EXISTS instructions JSONB; -- Store string[] as JSONB
ALTER TABLE ingredients ADD COLUMN IF NOT EXISTS chef_note TEXT;
ALTER TABLE ingredients ADD COLUMN IF NOT EXISTS prep_time TEXT;
ALTER TABLE ingredients ADD COLUMN IF NOT EXISTS cook_time TEXT;
ALTER TABLE ingredients ADD COLUMN IF NOT EXISTS total_time TEXT;


-- 3. PRODUCTS (Kitchen Management & Production)
ALTER TABLE products ADD COLUMN IF NOT EXISTS instructions JSONB; -- Store string[] as JSONB
ALTER TABLE products ADD COLUMN IF NOT EXISTS chef_note TEXT;
ALTER TABLE products ADD COLUMN IF NOT EXISTS prep_time TEXT;
ALTER TABLE products ADD COLUMN IF NOT EXISTS cook_time TEXT;
ALTER TABLE products ADD COLUMN IF NOT EXISTS total_time TEXT;
ALTER TABLE products ADD COLUMN IF NOT EXISTS stock NUMERIC DEFAULT 0; -- Initial stock for batch production


-- 4. JOB TITLES (If missing)
CREATE TABLE IF NOT EXISTS job_titles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    active BOOLEAN DEFAULT TRUE,
    permissions JSONB, -- Store string[] as JSONB
    restaurant_id UUID REFERENCES restaurants(id),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Enable RLS for job_titles if created
ALTER TABLE job_titles ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Enable all for authenticated users" ON job_titles;
CREATE POLICY "Enable all for authenticated users" ON job_titles FOR ALL USING (auth.role() = 'authenticated');


-- 5. DAILY CLOSES & CASH COUNTS (Ensuring status columns)
ALTER TABLE daily_closes ADD COLUMN IF NOT EXISTS status TEXT DEFAULT 'closed';
ALTER TABLE cash_counts ADD COLUMN IF NOT EXISTS details JSONB; -- Store denomination breakdown

-- 6. DTEs (Electronic Invoicing)
CREATE TABLE IF NOT EXISTS dtes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type INTEGER NOT NULL,
    folio INTEGER NOT NULL,
    date TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    amount NUMERIC NOT NULL,
    receiver_rut TEXT,
    receiver_name TEXT,
    receiver_address TEXT,
    xml_content TEXT,
    status TEXT, -- 'issued', 'received', 'voided'
    order_id BIGINT, -- Optional link
    restaurant_id UUID REFERENCES restaurants(id),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);
ALTER TABLE dtes ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Enable all for authenticated users" ON dtes;
CREATE POLICY "Enable all for authenticated users" ON dtes FOR ALL USING (auth.role() = 'authenticated');
