-- ============================================================================
-- KONTIGO POS - MASTER BOOTSTRAP SCRIPT (RECOVERY MODE)
-- ============================================================================
-- Run this script in Supabase SQL Editor to recreate the entire database structure.
-- Once created, your local POS will re-upload its data automatically.

create extension if not exists "uuid-ossp";

-- 1. TENANTS & AUTH
-- ============================================================================
create table if not exists restaurants (
  id uuid default uuid_generate_v4() primary key,
  name text not null,
  commerce_code text not null unique,
  owner_email text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  active boolean default true
);

-- 2. CORE MENU
-- ============================================================================
create table if not exists categories (
  id bigint generated by default as identity primary key,
  restaurant_id uuid references restaurants(id) on delete cascade,
  name text not null,
  destination text default 'kitchen',
  course text, -- 'starter', 'main', 'dessert'
  "order" integer default 0,
  deleted_at timestamp with time zone
);

create table if not exists modifier_templates (
  id bigint generated by default as identity primary key,
  restaurant_id uuid references restaurants(id) on delete cascade,
  name text not null,
  min_select integer default 0,
  max_select integer default 1,
  options jsonb default '[]'::jsonb -- [{name, price}]
);

create table if not exists products (
  id bigint generated by default as identity primary key,
  restaurant_id uuid references restaurants(id) on delete cascade,
  category_id bigint references categories(id),
  name text not null,
  price numeric default 0,
  image text,
  modifiers jsonb default '[]'::jsonb, -- stored as JSON since structure varies
  is_available boolean default true,
  stock numeric,
  
  -- Recipe & Prep
  instructions text[],
  chef_note text,
  prep_time text,
  cook_time text,
  total_time text,
  
  deleted_at timestamp with time zone
);

-- 3. INVENTORY
-- ============================================================================
create table if not exists suppliers (
    id bigint generated by default as identity primary key,
    restaurant_id uuid references restaurants(id) on delete cascade,
    name text not null,
    rut text,
    contact_name text,
    email text,
    phone text,
    lead_time_days integer default 0,
    category text,
    deleted_at timestamp with time zone
);

create table if not exists ingredients (
    id bigint generated by default as identity primary key,
    restaurant_id uuid references restaurants(id) on delete cascade,
    supplier_id bigint references suppliers(id),
    name text not null,
    stock numeric default 0,
    unit text,
    cost numeric default 0,
    min_stock numeric,
    yield_percent numeric,
    category text,
    purchase_unit text,
    conversion_factor numeric,
    code text,
    
    -- Categorization
    family text,
    sub_family text,
    storage text,
    is_infinite boolean default false,
    
    -- Prep
    is_preparation boolean default false,
    instructions text[],
    chef_note text,
    prep_time text,
    cook_time text
);

create table if not exists purchase_orders (
    id bigint generated by default as identity primary key,
    restaurant_id uuid references restaurants(id) on delete cascade,
    supplier_id bigint references suppliers(id),
    status text, -- 'draft', 'pending', 'received'
    total_cost numeric,
    items jsonb, -- [{ingredientId, quantity, cost}]
    created_at timestamp with time zone default now(),
    date timestamp with time zone -- Delivery Date
);

create table if not exists waste_logs (
    id bigint generated by default as identity primary key,
    restaurant_id uuid references restaurants(id) on delete cascade,
    date timestamp with time zone default now(),
    reason text,
    items jsonb -- [{ingredientId, quantity, cost}]
);

create table if not exists production_logs (
    id bigint generated by default as identity primary key,
    restaurant_id uuid references restaurants(id) on delete cascade,
    product_id bigint, -- Can be null if generic prep
    date timestamp with time zone,
    quantity numeric,
    status text, -- 'planned', 'completed'
    notes text
);

-- 4. STAFF & OPERATIONS
-- ============================================================================
create table if not exists restaurant_tables (
    id bigint generated by default as identity primary key,
    restaurant_id uuid references restaurants(id) on delete cascade,
    name text not null,
    zone text,
    capacity integer,
    status text default 'free',
    current_order_id bigint, -- Weak link, not FK to avoid circular deps with orders
    x integer,
    y integer
);

create table if not exists job_titles (
    id bigint generated by default as identity primary key,
    restaurant_id uuid references restaurants(id) on delete cascade,
    name text not null,
    active boolean default true,
    permissions text[]
);

create table if not exists restaurant_staff (
    id bigint primary key, -- BigInt to match Dexie
    restaurant_id uuid references restaurants(id) on delete cascade,
    name text not null,
    pin text,
    email text,
    role_name text,
    status text default 'active',
    
    -- Extended
    phone text,
    address text,
    rut text,
    nationality text,
    birth_date timestamp,
    contract_type text,
    contract_duration text,
    start_date timestamp,
    weekly_hours_limit integer,
    
    -- Finance
    salary_type text,
    base_salary numeric,
    afp text,
    health_system text,
    health_fee numeric,
    bank_details jsonb,
    
    created_at timestamp with time zone default now()
);

create table if not exists shifts (
    id bigint generated by default as identity primary key,
    restaurant_id uuid references restaurants(id) on delete cascade,
    staff_id bigint references restaurant_staff(id),
    start_time timestamp with time zone,
    end_time timestamp with time zone,
    scheduled_start timestamp with time zone,
    scheduled_end timestamp with time zone,
    status text, -- 'active', 'closed'
    is_overtime boolean default false,
    manager_approval text,
    auto_clock_out boolean
);

-- 5. SALES & FINANCE
-- ============================================================================
create table if not exists orders (
    id bigint primary key, -- BigInt matching Dexie
    restaurant_id uuid references restaurants(id) on delete cascade,
    table_id bigint,
    status text, -- 'open', 'closed', 'cancelled'
    total numeric,
    subtotal numeric,
    tip numeric,
    discount numeric,
    
    -- JSON Blobs for complex order data
    items jsonb, -- [{product, quantity, modifiers}]
    payments jsonb, -- [{method, amount}]
    
    staff_id bigint,
    customer_count integer,
    
    created_at timestamp with time zone,
    closed_at timestamp with time zone,
    
    -- KDS
    ready_sections text[]
);

create table if not exists dtes (
    id bigint generated by default as identity primary key,
    restaurant_id uuid references restaurants(id) on delete cascade,
    order_id bigint references orders(id),
    
    type integer, -- 39, 33, etc.
    folio integer,
    amount numeric,
    status text,
    
    receiver_rut text,
    receiver_name text,
    receiver_address text,
    
    xml_content text,
    pdf_url text,
    sii_track_id text,
    
    date timestamp with time zone default now()
);

create table if not exists cash_counts (
    id bigint generated by default as identity primary key,
    restaurant_id uuid references restaurants(id) on delete cascade,
    date timestamp with time zone default now(),
    amount numeric,
    type text, -- 'opening', 'closing', 'drop', 'pickup'
    staff_id bigint references restaurant_staff(id),
    shift_id bigint references shifts(id),
    
    notes text,
    details jsonb -- Denominations
);

create table if not exists daily_closes (
    id bigint generated by default as identity primary key,
    restaurant_id uuid references restaurants(id) on delete cascade,
    date timestamp with time zone default now(),
    status text, -- 'open', 'closed'
    
    total_sales numeric,
    total_cash numeric,
    total_card numeric,
    total_online numeric,
    total_tips numeric,
    
    opening_cash numeric,
    cash_difference numeric,
    dte_count integer,
    
    start_time timestamp with time zone,
    closed_by text
);

create table if not exists accounts (
    id bigint generated by default as identity primary key,
    restaurant_id uuid references restaurants(id) on delete cascade,
    code text not null,
    name text,
    type text, -- 'asset', 'liability', 'equity', 'revenue', 'expense'
    balance numeric default 0
);

create table if not exists journal_entries (
    id bigint generated by default as identity primary key,
    restaurant_id uuid references restaurants(id) on delete cascade,
    date timestamp with time zone default now(),
    description text,
    reference_id text, -- e.g. "ORDER-123"
    debit_account_code text,
    credit_account_code text,
    amount numeric,
    status text -- 'posted', 'draft'
);

create table if not exists customers (
    id bigint generated by default as identity primary key,
    restaurant_id uuid references restaurants(id) on delete cascade,
    name text,
    email text,
    phone text,
    points numeric default 0,
    total_spent numeric default 0,
    last_visit timestamp with time zone
);

-- 6. CONFIGURATION (New Stuff)
-- ============================================================================
create table if not exists api_keys (
    id bigint generated by default as identity primary key,
    restaurant_id uuid references restaurants(id) on delete cascade,
    name text,
    prefix text,
    key_hash text unique,
    status text default 'active',
    created_at timestamp with time zone default now(),
    last_used timestamp with time zone
);

-- The table we just added!
CREATE TABLE IF NOT EXISTS restaurant_config (
    id bigint generated by default as identity primary key,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    restaurant_id UUID references restaurants(id) on delete cascade,

    -- Identity
    fantasy_name TEXT,
    business_name TEXT,
    rut TEXT,
    address TEXT,
    phone TEXT,
    email TEXT,
    
    -- SII / DTE Credentials
    sii_environment TEXT,
    sii_certificate_p12 TEXT,
    sii_certificate_password TEXT,
    sii_api_key TEXT,
    
    -- Payment
    payment_provider TEXT,
    payment_terminal_id TEXT,

    UNIQUE(restaurant_id)
);

-- 7. ENABLE RLS (Row Level Security) ON EVERYTHING
-- ============================================================================
-- We use a simplified RLS model: "Authenticated users can see everything in their restaurant"
-- For a real multi-tenant app, you'd check profile.restaurant_id vs row.restaurant_id
-- For now, we allow ALL authenticated users full access (assuming backend/middleware handles tenant selection via app.current_restaurant_id)

-- Helper to enable RLS quickly
DO $$ 
DECLARE 
    t text;
BEGIN 
    FOR t IN 
        SELECT table_name FROM information_schema.tables WHERE table_schema = 'public' 
    LOOP 
        EXECUTE 'ALTER TABLE ' || t || ' ENABLE ROW LEVEL SECURITY';
        EXECUTE 'DROP POLICY IF EXISTS "Access own restaurant" ON ' || t;
        -- Simple permissive policy for now (refine later if needed)
        EXECUTE 'CREATE POLICY "Access own restaurant" ON ' || t || ' FOR ALL USING (true) WITH CHECK (true)';
    END LOOP; 
END $$;

-- 8. GRANT PERMISSIONS
GRANT ALL ON ALL TABLES IN SCHEMA public TO authenticated;
GRANT ALL ON ALL TABLES IN SCHEMA public TO service_role;
GRANT ALL ON ALL SEQUENCES IN SCHEMA public TO authenticated;
GRANT ALL ON ALL SEQUENCES IN SCHEMA public TO service_role;

SELECT '✅ SUCCESS: DATABASE RECREATED' as status;
