-- Create 'production_logs' table in Supabase
CREATE TABLE IF NOT EXISTS production_logs (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    product_id BIGINT REFERENCES products(id),
    product_name TEXT NOT NULL,
    quantity NUMERIC NOT NULL,
    date TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    staff_id BIGINT REFERENCES restaurant_staff(id),
    cost_per_unit NUMERIC,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Add RLS policies (Optional but recommended)
ALTER TABLE production_logs ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Enable read access for all users" ON production_logs FOR SELECT USING (true);
CREATE POLICY "Enable insert for all users" ON production_logs FOR INSERT WITH CHECK (true);
CREATE POLICY "Enable update for all users" ON production_logs FOR UPDATE USING (true);
