-- ==========================================
-- CREATE CASH REGISTER TABLES (Daily Closes & Counts)
-- ==========================================

-- 1. Daily Closes (Cierres Z)
CREATE TABLE IF NOT EXISTS public.daily_closes (
    id bigint generated by default as identity primary key,
    date timestamp with time zone default timezone('utc'::text, now()) not null,
    start_time timestamp with time zone,
    opening_cash numeric default 0,
    total_sales numeric default 0,
    total_cash numeric default 0,
    total_card numeric default 0,
    total_online numeric default 0,
    total_tips numeric default 0,
    dte_count integer default 0,
    cash_difference numeric default 0,
    closed_by text,
    status text default 'closed' -- 'open' or 'closed'
);

ALTER TABLE public.daily_closes ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Enable all access for daily_closes" ON public.daily_closes;
CREATE POLICY "Enable all access for daily_closes" ON public.daily_closes FOR ALL USING (true) WITH CHECK (true);


-- 2. Cash Counts (Arqueos / Conteos)
CREATE TABLE IF NOT EXISTS public.cash_counts (
    id bigint generated by default as identity primary key,
    shift_id bigint, -- Optional link to a specific shift
    staff_id bigint references public.restaurant_staff(id),
    date timestamp with time zone default timezone('utc'::text, now()) not null,
    declared_cash numeric default 0,
    system_cash numeric default 0,
    difference numeric default 0,
    notes text,
    details jsonb default '[]'::jsonb -- Stores array of {denomination, quantity}
);

ALTER TABLE public.cash_counts ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Enable all access for cash_counts" ON public.cash_counts;
CREATE POLICY "Enable all access for cash_counts" ON public.cash_counts FOR ALL USING (true) WITH CHECK (true);

-- 3. Grants (Just in case)
GRANT ALL ON TABLE public.daily_closes TO authenticated;
GRANT ALL ON TABLE public.daily_closes TO service_role;
GRANT ALL ON TABLE public.daily_closes TO anon;

GRANT ALL ON TABLE public.cash_counts TO authenticated;
GRANT ALL ON TABLE public.cash_counts TO service_role;
GRANT ALL ON TABLE public.cash_counts TO anon;
