-- Create Job Titles table for role management
CREATE TABLE IF NOT EXISTS public.job_titles (
    id bigint generated by default as identity primary key,
    name text not null,
    active boolean default true,
    permissions text[] default '{}', -- Stores array of permission strings
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Add unique constraint on name to prevent duplicates
ALTER TABLE public.job_titles ADD CONSTRAINT job_titles_name_key UNIQUE (name);

-- Enable RLS
ALTER TABLE public.job_titles ENABLE ROW LEVEL SECURITY;

-- Create policy to allow all access (since this is a single-tenant local-first app sync)
CREATE POLICY "Enable all access for all users" ON public.job_titles FOR ALL USING (true) WITH CHECK (true);
