-- Create Salary Settlements Table for Historical storage
CREATE TABLE IF NOT EXISTS public.salary_settlements (
    id bigint generated by default as identity primary key,
    
    -- Link to Staff (Use bigint to match your current schema fix)
    staff_id bigint references public.restaurant_staff(id) on delete cascade not null,
    
    -- Period Identification
    period_month integer not null, -- 1-12
    period_year integer not null,  -- e.g. 2025
    
    -- Financial Snapshot (Stores the frozen values at time of generation)
    base_salary numeric not null,
    gratification numeric not null,
    total_imponible numeric not null,
    total_descuentos numeric not null,
    total_haberes numeric not null,
    liquid_salary numeric not null,
    
    -- Full Calculation Data (JSON dump of the logic output for auditing)
    calculation_snapshot jsonb not null, 
    
    -- Document Storage
    pdf_url text, -- Path to Supabase Storage bucket
    
    -- Metadata
    created_at timestamp with time zone default timezone('utc'::text, now()) not null,
    finalized boolean default false, -- If true, should not be deleted/edited easily
    
    -- Unique constraint: One settlement per staff per month (usually)
    UNIQUE(staff_id, period_month, period_year)
);

-- Enable RLS
ALTER TABLE public.salary_settlements ENABLE ROW LEVEL SECURITY;

-- Policies (Adjust based on your Auth setup, assuming full access for authenticated users for now)
create policy "Enable all access for authenticated users" on public.salary_settlements
  for all using (true) with check (true);

-- Storage Bucket Policy (You'll need to create the 'payroll-docs' bucket in Supabase Dashboard)
-- insert into storage.buckets (id, name, public) values ('payroll-docs', 'payroll-docs', false);
