-- -----------------------------------------------------------------------------
-- PRODUCTION FORECASTING MODULE
-- -----------------------------------------------------------------------------

-- 1. Sales History Log
-- Stores daily summary of sales per item for forecasting.
create table if not exists public.sales_history_log (
  id bigint generated by default as identity primary key,
  date date not null,
  menu_item_id bigint references public.products(id) on delete cascade, -- Mapped to 'products'
  quantity_sold int not null default 0,
  day_of_week int not null check (day_of_week between 0 and 6) -- 0=Sunday, 6=Saturday
);

-- Indexes for fast lookup by item and day (e.g., "How many burgers sell on Mondays?")
create index if not exists idx_sales_history_item_day 
  on public.sales_history_log(menu_item_id, day_of_week);

create index if not exists idx_sales_history_date 
  on public.sales_history_log(date);


-- 2. Production Plans
-- Daily kitchen production orders.
create table if not exists public.production_plans (
  id bigint generated by default as identity primary key,
  target_date date not null,
  status text check (status in ('pending', 'completed', 'verified')) default 'pending',
  created_at timestamptz default now()
);


-- 3. Production Plan Items
-- Details of what to prep for a specific plan.
create table if not exists public.production_plan_items (
  id bigint generated by default as identity primary key,
  plan_id bigint references public.production_plans(id) on delete cascade,
  ingredient_id bigint references public.ingredients(id) on delete cascade, -- Mapped to 'ingredients'
  recipe_id bigint, -- Optional, if tracking specific sub-recipes
  suggested_qty float not null default 0,
  actual_qty_prepped float default 0, -- Filled by kitchen staff
  unit text -- 'kg', 'ltr', etc. (Denormalized for convenience)
);

create index if not exists idx_production_items_plan 
  on public.production_plan_items(plan_id);


-- 4. Function: Get Average Sales for Last 4 Weeks
-- Calculates the average sales of a specific item on a specific day of the week
-- looking back 4 weeks from the current date.
create or replace function get_avg_sales_last_4_weeks(
  p_item_id bigint, 
  p_day_int int
)
returns float
language plpgsql
as $$
declare
  v_avg_sales float;
begin
  select coalesce(avg(quantity_sold), 0)
  into v_avg_sales
  from sales_history_log
  where menu_item_id = p_item_id
    and day_of_week = p_day_int
    and date >= (current_date - interval '28 days'); -- Last 4 weeks
  
  return v_avg_sales;
end;
$$;

-- Comments
comment on table public.sales_history_log is 'Historical sales data for forecasting models.';
comment on table public.production_plans is 'Daily production plans generated by the Forecasting Engine.';
