-- ==========================================
-- KONTIGO POS - FINAL SETUP SCRIPT
-- ==========================================
-- Runs all necessary migrations to ensure:
-- 1. Sync works (Tenants + Roles)
-- 2. FKs work (BigInt IDs)
-- 3. Data is safe (Clean migration)

-- A. EXTENSIONS
create extension if not exists "uuid-ossp";

-- B. TENANTS (Restaurants)
create table if not exists restaurants (
  id uuid default uuid_generate_v4() primary key,
  name text not null,
  commerce_code text not null unique,
  owner_email text not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  active boolean default true
);
alter table restaurants enable row level security;
DROP POLICY IF EXISTS "Enable all access for restaurants" ON restaurants;
create policy "Enable all access for restaurants" on restaurants for all using (true) with check (true);

-- C. JOB TITLES (Dynamic Roles) - REQUIRED FOR "Gestionar Cargos"
create table if not exists job_titles (
    id bigint generated by default as identity primary key,
    name text not null unique,
    active boolean default true,
    permissions text[] default '{}',
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);
alter table job_titles enable row level security;
DROP POLICY IF EXISTS "Enable all access for job_titles" ON job_titles;
create policy "Enable all access for job_titles" on job_titles for all using (true) with check (true);


-- D. FIX RESTAURANT STAFF (The "Cloud" version of Staff)
-- 1. Drop constraints from dependent tables (if they exist)
DO $$ 
BEGIN
    IF EXISTS (SELECT 1 FROM information_schema.table_constraints WHERE constraint_name = 'shifts_staff_id_fkey') THEN
        ALTER TABLE public.shifts DROP CONSTRAINT shifts_staff_id_fkey;
    END IF;
    IF EXISTS (SELECT 1 FROM information_schema.table_constraints WHERE constraint_name = 'orders_staff_id_fkey') THEN
        ALTER TABLE public.orders DROP CONSTRAINT orders_staff_id_fkey;
    END IF;
    IF EXISTS (SELECT 1 FROM information_schema.table_constraints WHERE constraint_name = 'cash_counts_staff_id_fkey') THEN
        ALTER TABLE public.cash_counts DROP CONSTRAINT cash_counts_staff_id_fkey;
    END IF;
END $$;

-- 2. Drop the table if it exists (to recreate with correct ID type)
DROP TABLE IF EXISTS public.restaurant_staff CASCADE;

-- 3. Recreate with BIGINT ID
create table restaurant_staff (
  id bigint primary key, -- Matches Dexie ID
  restaurant_id uuid references restaurants(id) on delete cascade not null,
  name text not null,
  role_name text not null, -- Renamed BACK to role_name because generic sync service maps 'role' -> 'role_name'
  role_permissions jsonb default '[]'::jsonb,
  active boolean default true,
  pin text,
  email text,
  
  -- Extended Fields (Matches Staff interface)
  avatar_color text,
  phone text,
  rut text,
  address text,      -- Added
  nationality text,  -- Added
  birth_date timestamp, -- Added
  
  status text default 'active',
  contract_type text,
  contract_duration text, -- Added
  start_date timestamp,   -- Added
  weekly_hours_limit integer,
  active_role text,
  
  -- Financial & Payroll
  salary_type text,
  base_salary numeric,
  gratification boolean default true,
  colacion numeric default 0,
  movilizacion numeric default 0,
  estimated_tips numeric default 0,
  
  -- Social Security
  afp text,
  health_system text,
  health_fee numeric,
  seguro_cesantia boolean default true,
  
  -- Json Blobs for complex data
  bank_details jsonb,
  
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);
alter table restaurant_staff enable row level security;
DROP POLICY IF EXISTS "Enable all access for restaurant_staff" ON restaurant_staff;
create policy "Enable all access for restaurant_staff" on restaurant_staff for all using (true) with check (true);

-- E. RE-CONNECT FKs (Pointing to new BigInt Table)
-- Only run if the tables exist
DO $$ 
BEGIN
    IF EXISTS (SELECT FROM pg_tables WHERE schemaname = 'public' AND tablename = 'shifts') THEN
        ALTER TABLE public.shifts ADD CONSTRAINT shifts_staff_id_fkey FOREIGN KEY (staff_id) REFERENCES public.restaurant_staff(id);
    END IF;
    IF EXISTS (SELECT FROM pg_tables WHERE schemaname = 'public' AND tablename = 'orders') THEN
        ALTER TABLE public.orders ADD CONSTRAINT orders_staff_id_fkey FOREIGN KEY (staff_id) REFERENCES public.restaurant_staff(id);
    END IF;
    IF EXISTS (SELECT FROM pg_tables WHERE schemaname = 'public' AND tablename = 'cash_counts') THEN
        ALTER TABLE public.cash_counts ADD CONSTRAINT cash_counts_staff_id_fkey FOREIGN KEY (staff_id) REFERENCES public.restaurant_staff(id);
    END IF;
END $$;

-- F. CLEANUP
DROP TABLE IF EXISTS public.staff;

-- G. PROACTIVE UPDATES (Inventory & Menu)
-- Ensure these tables have the new columns from your local DB

-- 1. Ingredients
CREATE TABLE IF NOT EXISTS public.ingredients (id bigint generated by default as identity primary key, name text);
ALTER TABLE public.ingredients ADD COLUMN IF NOT EXISTS family text;
ALTER TABLE public.ingredients ADD COLUMN IF NOT EXISTS "subFamily" text; -- Note camelCase in DB needs quotes if mapped strictly, but verify snake_case in sync. Assuming auto-snake-case: sub_family
ALTER TABLE public.ingredients ADD COLUMN IF NOT EXISTS sub_family text; -- Providing snake_case target
ALTER TABLE public.ingredients ADD COLUMN IF NOT EXISTS storage text;
ALTER TABLE public.ingredients ADD COLUMN IF NOT EXISTS is_infinite boolean default false;
ALTER TABLE public.ingredients ADD COLUMN IF NOT EXISTS is_preparation boolean default false;
ALTER TABLE public.ingredients ADD COLUMN IF NOT EXISTS instructions text[]; -- Array of strings
ALTER TABLE public.ingredients ADD COLUMN IF NOT EXISTS chef_note text;
ALTER TABLE public.ingredients ADD COLUMN IF NOT EXISTS prep_time text;
ALTER TABLE public.ingredients ADD COLUMN IF NOT EXISTS cook_time text;
ALTER TABLE public.ingredients ADD COLUMN IF NOT EXISTS total_time text;

-- 2. Products
CREATE TABLE IF NOT EXISTS public.products (id bigint generated by default as identity primary key, name text);
ALTER TABLE public.products ADD COLUMN IF NOT EXISTS instructions text[];
ALTER TABLE public.products ADD COLUMN IF NOT EXISTS chef_note text;
ALTER TABLE public.products ADD COLUMN IF NOT EXISTS prep_time text;
ALTER TABLE public.products ADD COLUMN IF NOT EXISTS cook_time text;
ALTER TABLE public.products ADD COLUMN IF NOT EXISTS total_time text;

-- 3. Suppliers
CREATE TABLE IF NOT EXISTS public.suppliers (id bigint generated by default as identity primary key, name text);
ALTER TABLE public.suppliers ADD COLUMN IF NOT EXISTS lead_time_days integer;

-- 4. Enable RLS for these tables to ensure they are accessible
alter table public.ingredients enable row level security;
drop policy if exists "Enable all access for ingredients" on public.ingredients;
create policy "Enable all access for ingredients" on public.ingredients for all using (true) with check (true);

alter table public.products enable row level security;
drop policy if exists "Enable all access for products" on public.products;
create policy "Enable all access for products" on public.products for all using (true) with check (true);

alter table public.suppliers enable row level security;
drop policy if exists "Enable all access for suppliers" on public.suppliers;
create policy "Enable all access for suppliers" on public.suppliers for all using (true) with check (true);

alter table public.categories enable row level security;
drop policy if exists "Enable all access for categories" on public.categories;
create policy "Enable all access for categories" on public.categories for all using (true) with check (true);

alter table public.restaurant_tables enable row level security;
drop policy if exists "Enable all access for restaurant_tables" on public.restaurant_tables;
create policy "Enable all access for restaurant_tables" on public.restaurant_tables for all using (true) with check (true);

