-- PASO 0: CREAR TABLA STAFF SI NO EXISTE (CRÍTICO)
CREATE TABLE IF NOT EXISTS public.staff (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name TEXT NOT NULL,
    pin TEXT,
    role TEXT,
    status TEXT DEFAULT 'active',
    email TEXT,
    phone TEXT,
    active_role TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- PASO 1: ESTRUCTURA PRINCIPAL
CREATE TABLE IF NOT EXISTS public.restaurants (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    name TEXT NOT NULL,
    owner_email TEXT,
    commerce_code TEXT,
    active BOOLEAN DEFAULT TRUE,
    plan_status TEXT DEFAULT 'active',
    trial_ends_at TIMESTAMPTZ DEFAULT (now() + interval '14 days'),
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- PASO 2: COLUMNAS MULTI-TENANT (Iterativo seguro)
DO $$
DECLARE
    tables_to_update TEXT[] := ARRAY[
        'products', 'categories', 'ingredients', 'suppliers', 
        'purchase_orders', 'waste_logs', 'customers', 'restaurant_tables', 
        'orders', 'staff', 'shifts', 'printers', 'modifier_templates', 
        'dtes', 'cash_counts', 'daily_closes', 'job_titles', 
        'accounts', 'journal_entries', 'production_logs', 'settings'
    ];
    tbl TEXT;
BEGIN
    FOREACH tbl IN ARRAY tables_to_update LOOP
        -- Solo alteramos si la tabla existe
        IF EXISTS (SELECT FROM pg_tables WHERE schemaname = 'public' AND tablename = tbl) THEN
            EXECUTE format('ALTER TABLE public.%I ADD COLUMN IF NOT EXISTS restaurant_id UUID REFERENCES public.restaurants(id);', tbl);
            -- Crear índice si no existe (nombre único truncado para evitar errores)
            EXECUTE format('CREATE INDEX IF NOT EXISTS idx_%I_rest_id ON public.%I(restaurant_id);', substring(tbl from 1 for 20), tbl);
        END IF;
    END LOOP;
END $$;

-- PASO 3: MIGRACIÓN DE DATOS (Dinámico para no fallar si falta una tabla)
DO $$
DECLARE
    my_rest_id UUID;
    tbl TEXT;
    tables_to_migrate TEXT[] := ARRAY[
        'products', 'categories', 'ingredients', 'suppliers', 
        'orders', 'staff', 'shifts', 'customers', 'daily_closes'
    ];
BEGIN
    -- 1. Crear/Obtener Restaurante
    INSERT INTO public.restaurants (name, owner_email, active, commerce_code)
    VALUES ('Malas Juntas', 'admin@kontigo.cl', true, 'MJ-LEGACY-001')
    ON CONFLICT DO NOTHING;

    SELECT id INTO my_rest_id FROM public.restaurants WHERE name LIKE 'Malas Juntas%' LIMIT 1;

    -- 2. Actualizar Datos SOLO si la tabla existe
    IF my_rest_id IS NOT NULL THEN
        FOREACH tbl IN ARRAY tables_to_migrate LOOP
            IF EXISTS (SELECT FROM pg_tables WHERE schemaname = 'public' AND tablename = tbl) THEN
                EXECUTE format('UPDATE public.%I SET restaurant_id = %L WHERE restaurant_id IS NULL;', tbl, my_rest_id);
                RAISE NOTICE 'Migrated table: %', tbl;
            ELSE
                RAISE NOTICE 'Skipping missing table: %', tbl;
            END IF;
        END LOOP;
    END IF;
END $$;
